# Generated by Django 4.0.4 on 2022-05-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0002_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='price',
            field=models.FloatField(),
        ),
    ]
