# Generated by Django 4.0.4 on 2022-05-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0004_remove_storeinventory_warehouseinventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventory',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='warehouseInventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='InventoryManagement.warehouseinventory'),
            preserve_default=False,
        ),
    ]
