# Generated by Django 4.0.4 on 2022-05-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0005_remove_storeinventory_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinventory',
            name='warehouseInventory',
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='InventoryManagement.warehouse'),
            preserve_default=False,
        ),
    ]
