# Generated by Django 4.0.4 on 2022-05-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0007_rename_supplier_supplierprice_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='个', max_length=50),
            preserve_default=False,
        ),
    ]
