# Generated by Django 4.0.4 on 2022-05-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0007_rename_supplier_supplierprice_supplier_and_more'),
        ('PeopleManagement', '0002_remove_salesmanager_store_user_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store',
        ),
        migrations.AddField(
            model_name='salesmanager',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='InventoryManagement.store'),
            preserve_default=False,
        ),
    ]
