# Generated by Django 4.0.4 on 2022-05-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PeopleManagement', '0001_initial'),
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryManagement.product')),
                ('salesPerson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PeopleManagement.user')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryManagement.supplier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryManagement.product')),
            ],
        ),
    ]
