# Generated by Django 4.0.4 on 2022-05-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManagement', '0002_alter_salesprice_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='date',
            field=models.DateField(default='2022-05-01'),
            preserve_default=False,
        ),
    ]
