# Generated by Django 4.0.4 on 2022-05-02 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0003_alter_product_sell_price_alter_supplierprice_price'),
        ('SalesManagement', '0003_salesrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='InventoryManagement.store'),
            preserve_default=False,
        ),
    ]
