# Generated by Django 4.0.4 on 2022-06-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0008_product_unit'),
        ('SalesManagement', '0004_salesrecord_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesprice',
            name='purchase_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryManagement.supplierprice'),
        ),
    ]
