# Generated by Django 4.0.4 on 2022-06-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManagement', '0005_alter_salesprice_purchase_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesPrice',
        ),
    ]
