# Generated by Django 3.2.5 on 2022-06-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManagement', '0006_delete_salesprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
